### ISSUE TITLE
update description in the .cabal file

### ISSUE THREAD

**Issue by p4l1ly** [fpco/ghc-prof-flamegraph#17]
The description on hackage still states that the output should be postprocessed using `flamegraph.pl` which is no more true. Instead of maintaining two examples of use, you might want to link it instead to this README.

btw thank you a lot for your work, it has saved me plenty of time :)

**Comment by UnkindPartition** [comment]
I second everything @p4l1ly says. Please let us know if it would help if we opened a PR.

**Comment by bitonic** [comment]
Sorry about the delay -- been a bit busy. I will welcome PRs rectifying these problems!
